// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5XAZgWeki8Efg3znWF1fdH3jO-lPoZWM',
    appId: '1:237630468649:android:0c641dab41386189586238',
    messagingSenderId: '237630468649',
    projectId: 'kurdwork-99',
    storageBucket: 'kurdwork-99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3_r8wlIVYQ3b189I-Icg0H1pC3aLq6k',
    appId: '1:237630468649:ios:32aa8ae63f97c08f586238',
    messagingSenderId: '237630468649',
    projectId: 'kurdwork-99',
    storageBucket: 'kurdwork-99.appspot.com',
    iosClientId:
        '237630468649-vv2ig7jgle00pvtks55leldbuslqtprt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurdwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3_r8wlIVYQ3b189I-Icg0H1pC3aLq6k',
    appId: '1:237630468649:ios:32aa8ae63f97c08f586238',
    messagingSenderId: '237630468649',
    projectId: 'kurdwork-99',
    storageBucket: 'kurdwork-99.appspot.com',
    iosClientId:
        '237630468649-vv2ig7jgle00pvtks55leldbuslqtprt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurdwork',
  );
}
