const users = [
  {
    'username': 'harrem99',
    'email': 'haremmhamad99@gmail.com',
    'phoneNo': '07703845087',
    'password': 'hhhhh123',
    'fname': 'هەرێم',
    'lname': 'محەمەد',
    'birthdate': '09-09-1999',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 5,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
  {
    'username': 'peshawa00',
    'email': 'peshawa00@gmail.com',
    'phoneNo': '07701234556',
    'password': 'ppppp123',
    'fname': 'پێشەوا',
    'lname': 'عسمان',
    'birthdate': '٠١-٠١،٢٠٠٠',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 2,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
  {
    'username': 'binar01',
    'email': 'binar01@gmail.com',
    'phoneNo': '07701234567',
    'password': 'hhhhh123',
    'fname': 'بینەر',
    'lname': 'کەریم',
    'birthdate': '02-04-1998',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 3,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
  {
    'username': 'hooshyar22',
    'email': 'hooshyar22@gmail.com',
    'phoneNo': '07701234567',
    'password': 'hhhhh123',
    'fname': 'هۆشیار',
    'lname': 'محەمەد',
    'birthdate': '01-01-1990',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 4,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
  {
    'username': 'ahmed23',
    'email': 'haremmhamad99@gmail.com',
    'phoneNo': '07701234567',
    'password': 'aaaaa123',
    'fname': 'ئەحمەد',
    'lname': 'محەمەد',
    'birthdate': '07-03-1994',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 1,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
  {
    'username': 'marwan55',
    'email': 'haremmhamad99@gmail.com',
    'phoneNo': '07703845087',
    'password': 'hhhhh123',
    'fname': 'هەرێم',
    'lname': 'عەباس',
    'birthdate': '05-11-1997',
    'profilePic': 'url',
    'bio': 'من گەشەپێداری مۆبایل ئاپ و یاری ئەلیکرۆنی و وێبم.',
    'rating': 3.5,
    'followers': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
    'following': ['karzan', 'Mariwan', 'Mhamad', 'Jacob'],
  },
];
